### PR TITLE
Add Leaflet Maps to 3rd party resources section

### PR DESCRIPTION
**Pull request by villeristi**
### Changes proposed in this pull request

-  Add Leaflet Maps to 3rd party resources section

### CODE REVIEW

**Comment by tw2113** [comment]
Fine with me if it's fine with @jtsternberg as well

**Comment by villeristi** [comment]
@jtsternberg @tw2113 any thoughts?

**Comment by jtsternberg** [comment]
@villeristi yes, i have thoughts, they are in the review. Please see above.

**Comment by tw2113** [comment]
Touched up fresh. Still gave props.

See: ba02322

**Pull request closed without merging**
