### PR TITLE
Added Select2 Post Field

### PR DESCRIPTION
**Pull request by mattkrupnik**
### Changes proposed in this pull request

In 3rd party resources section added new field

### CODE REVIEW

**Comment by jtsternberg** [comment]
Thank you for submitting. We already have a select2 field type highlighted on the readme:
!()[http://b.ustin.co/MZrt]

I wouldn't mind adding yours if you can outline any differences from the other one.

**Comment by mattkrupnik** [comment]
Ok, I thought that this one you selected does not allow searching posts - I missed that information that **it is possible** - https://gist.github.com/mustardBees/f970b89dc45876524c8e
My bad ;(

**Comment by jtsternberg** [comment]
It does, but unfortunately it's not an ajax solution. Does yours work with ajax-search?

**Comment by tw2113** [comment]
Closing for the time being. If the proposed field type becomes different enough from the one we already have listed to justify, we'll re-evaluate at that time.

Thanks.

**Pull request closed without merging**
