### PR TITLE
Repeatable css

### PR DESCRIPTION
**Pull request by anhskohbo**
See https://github.com/WebDevStudios/CMB2/issues/780

I'ts not done, I still fix some bugs.

Some screenshots:

On category edit:
screenshot from 2016-10-26 22-44-19

In a group field:
screenshot from 2016-10-26 22-45-31

In default metabox:
screenshot from 2016-10-26 22-45-01

### CODE REVIEW

**Comment by slaFFik** [comment]
@anhskohbo  
Will there be any other commits?

**Comment by anhskohbo** [comment]
@slaFFik Yes, it's still some bugs, but I'm so busy with my current work. I will finish this ASAP.

**Comment by anhskohbo** [comment]
I created a new pull request https://github.com/WebDevStudios/CMB2/pull/819

**Comment by tw2113** [comment]
Let's leave the issue open until any merge has occurred.

**Pull request closed without merging**
