### PR TITLE
Make repeatable fields drag sortable

### LINKED ISSUE #155: Repeater Drag and Drop
Hey guys! Thanks for all the hard work here!!

I just wanted to check and see if there are any plans to make the repeater fields support drag and drop re-ordering.

### PR DESCRIPTION
**Pull request by lipemat**
Fixes #155.

Global support for any field that is repeatable to be sorted via drag drop.

Implement using the same sortable api following the patten of cmb.makeListSortable()
Some minor CSS changes to have a move cursor and borders around the item being dragged.

### CODE REVIEW

**Comment by adriantoll** [comment]
Hello @lipemat - just trying this out, but my main use case is repeatable group fields. I've tried this and it doesn't seem to work for groups. Looking at the code that seems to make sense because cmb.makeRepeatableSortable() only references .cmb-field-list and .cmb-repeat-row. Great that you're working on this, so this isn't a criticism at all, but just wanted to make sure that what I've said is correct?

**Comment by lipemat** [comment]
Hi @adriantoll 
Because repeatable groups already have support for ordering I have not done any work on making them drag sort-able. 
Sounds like that would be a nice enhancement. Probably deserves it's own pull.

**Comment by adriantoll** [comment]
OK - thanks for the clarification. I didn't realise fields weren't sortable at all because I've always done it with groups...

**Comment by jtsternberg** [comment]
Hey guys, wanted to jump in and let you know I’m excited to test these out and hopefully get them merged, but it may be a bit before I get to. Thank you so much for putting the effort in to contribute. 

If you haven’t yet, please be sure to check out the contributing doc as that will make the review process smoother: https://github.com/CMB2/CMB2/blob/trunk/CONTRIBUTING.md

Thanks again!

**Comment by jtsternberg** [comment]
Tested and works well! Thank you!

**Comment by ljsherlock** [comment]
Hi guys and @lipemat thanks for the great work. Maybe I'm being really stupid, but I can't get this working. 

Is the option: "sortable: true" all that should be required?

Thanks!

**Comment by ljsherlock** [comment]
> Hi guys and @lipemat thanks for the great work. Maybe I'm being really stupid, but I can't get this working.
> 
> Is the option: "sortable: true" all that should be required?
> 
> Thanks!

Please ignore. I didn't realise that repeatable groups was a separate (open) pull: #1145 .

**Pull request merged**
