### PR TITLE
Make travis happy

### PR DESCRIPTION
**Pull request by anhskohbo**

### CODE REVIEW

**Comment by jtsternberg** [comment]
Thank you!

**Comment by anhskohbo** [comment]
Still have a test failed. in https://github.com/CMB2/CMB2/blob/develop/tests/bin/run-wp-unit-tests.sh#L29 you need to remove `exit 1`, some PHP warning can through that.

**Comment by jtsternberg** [comment]
ok, will try

**Comment by jtsternberg** [comment]
Still no luck.

**Pull request merged**
