### PR TITLE
Include .CodeMirror class in sortable exclusions

### LINKED ISSUE #1299: Repeatable CodeMirror textarea cannot click/drag to highlight text
## Expected Behavior:
Repeatable `textarea_code` fields that utilize CodeMirror for the editor should allow you to click and drag the text within to highlight the text.

## Actual Behavior:
Clicking and dragging inside a `textarea_code` field with CodeMirror enabled will cause the entire field to begin dragging.

## Possible Solution
In the `cmb.makeRepeatableSortable()` JS function, update the parameters passed to `.sortable()`. We would need to add `.CodeMirror` to the [existing defaults](https://api.jqueryui.com/sortable/#method-cancel), like this:

```js
$repeatables.sortable({
	items : '.cmb-repeat-row',
	cursor: 'move',
	cancel: 'input,textarea,button,select,option,.CodeMirror'
});
```

### Possible Solution's Risk Level
Low risk.

## Steps to reproduce (I have confirmed I can reproduce this issue on the [`develop`](https://github.com/CMB2/CMB2/tree/develop) branch):
1. Register a repeatable `textarea_code` field, and do not disable code mirror.
2. Add a second field to the group
3. Try to click and drag to select text within one of the fields. The entire block will begin to move instead of only the text being highlighted.

## CMB2 Field Registration Code:

This example includes the `after_field` property which outputs inline JS. This temporarily resolves the issue with the CodeMirror areas until CMB2 can be updated.

```php
add_action( 'cmb2_init', 'presentation_fields' );
function presentation_fields() {
	$prefix = '_jpry_field_';
	$cmb    = new_cmb2_box( [
		'id'           => 'presentation_slides',
		'title'        => 'Presentation Slides',
		'object_types' => [ 'jpry_presentation' ],
		'context'      => 'normal',
		'priority'     => 'high',
	] );

	$script = <<<'HTML'
<script>
jQuery( document ).on( 'cmb_init', function( e, cmb ) {
var $repeatables = cmb.metabox().find( '#_jpry_field_slides_repeat .cmb-field-list' );

$repeatables.sortable( "option", "cancel", "input,textarea,button,select,option,.CodeMirror" );
} );
</script>
HTML;

	// Add all the fields.
	$cmb->add_field( [
		'desc'        => 'Individual slides.',
		'id'          => $prefix . 'slides',
		'name'        => 'Slides',
		'repeatable'  => true,
		'type'        => 'textarea_code',
		'options'     => [
			'add_row_text' => 'Add Slide',
		],
		'attributes'  => [
			'data-codeeditor' => json_encode( [
				'codemirror' => [
					'mode'         => 'gfm',
					'lineWrapping' => true,
					'lineNumbers'  => false,
					'dragDrop'     => false,
				],
			] ),
		],
		'after_field' => $script,
	] );
}
```

## Your Environment
Browser name and version: Safari 12.1.2
Operating System and version (desktop or mobile): MacOS 10.14.6
WordPress version: 5.2.3

### PR DESCRIPTION
**Pull request by JPry**
Fixes #1299.

## Description
See #1299 for more details.

## Risk Level
Low.

## Testing procedure
1. Clear browser cache if necessary
1. Follow the steps outlined in #1299 to create a repeatable `textarea_code` field
1. Click and drag to try to select text in the CodeMirror area. The whole block should **not** drag

## Types of changes
- **Bug fix (non-breaking change which fixes an issue)**

## Checklist:
- [x] My code follows the code style of this project.
- [x] My code and pull requests meets the [Contributing guidelines](https://github.com/CMB2/CMB2/blob/develop/CONTRIBUTING.md).

### CODE REVIEW

**Comment by tw2113** [comment]
I'm fine with this, but want @jtsternberg chiming in too.

**Comment by salcode** [comment]
@JPry Great catch and overall this fix looks good to me.

What do you think about adding a comment before the `cancel` attribute like the following

```
// The default "cancel" attributes are: "input,textarea,button,select,option"
// See https://api.jqueryui.com/sortable/#option-cancel
```

My lack of jQuery UI knowledge made me slow to fully understand this PR and I think a comment like that would help me.

## Alternatively

As I was typing this, I realized a slightly more verbose code version could eliminate the need for the clarifying comment. e.g.

```
var cancelDefaultValue = $.ui.sortable.prototype.options.cancel;
$repeatables.sortable({
	items : '.cmb-repeat-row',
	cursor: 'move',
	cancel: cancelDefaultValue + ',.CodeMirror'
});
```

I think either approach would be helpful for making this change a little easier for a person (at least me 😀) to mentally parse quickly.

**Comment by jtsternberg** [comment]
Thanks @JPry! Good to "hear" from you. :)
I updated with the suggested comment @salcode, thank you for reviewing!

**Comment by JPry** [comment]
@jtsternberg Good to "hear" from you too 🙂 Hope you and your family are staying safe through Hurricane Dorian.

Thanks for getting this merged!

**Pull request merged**
