### PR TITLE
add apply_filters for the output html row

### PR DESCRIPTION
**Pull request by polupraneeth**
It filter will help create tabs and have more control on output html row - https://github.com/stackadroit/cmb2-extensions

### CODE REVIEW

**Comment by tw2113** [comment]
I'd argue it'd be best to turn on the output buffering after the potential early returns. Would be curious to see how turning that on, and then returning early, affected things, if at all.

**Comment by polupraneeth** [comment]
Hi, @tw2113 sorry I am not to good in English, unable to understand your comment. Should i have to make some changes ?

**Comment by tw2113** [comment]
Basically move line 814, the `ob_start();`, to line 825

**Comment by polupraneeth** [comment]
Done, moved the  ob_start() to line 825 :)

**Comment by jtsternberg** [comment]
You can already override the render callback: https://github.com/CMB2/CMB2/blob/develop/example-functions.php#L200
Closing unless a compelling argument can be made for needing this filter instead of using the available field parameter, `render_row_cb`.

**Pull request closed without merging**
