### PR TITLE
Repeatable Styles

### PR DESCRIPTION
**Pull request by anhskohbo**
Fixes https://github.com/WebDevStudios/CMB2/issues/780

Some screenshots:

On category edit:
screenshot from 2016-10-26 22-44-19

In a group field:
screenshot from 2016-10-26 22-45-31

In default metabox:
screenshot from 2016-10-26 22-45-01

### CODE REVIEW

**Comment by anhskohbo** [comment]
ping @jtsternberg

**Comment by anhskohbo** [comment]
Anyone review this?

**Comment by jtsternberg** [comment]
Hey @anhskohbo, thank you for submitting. I'm slammed for the next month or two. I'll ping @gregrickaby or @coreymcollins to see if they might have an opportunity to review this PR.

**Comment by Mte90** [comment]
any news for that pr?

**Comment by anhskohbo** [comment]
I just refresh the code. Any update for this 6 months pull-request? :)

**Comment by jtsternberg** [comment]
I like it @anhskohbo, nice work. We'll see what kind of feedback we get when people update CMB2. :)

**Comment by anhskohbo** [comment]
Thanks!

**Pull request merged**
